### ISSUE TITLE
Communication With PLC

### ISSUE THREAD

**Issue by dedhdude** [synapticon/ecatmod#1]
Can This communicate with backoff PLC?
And if yes then how?

**Comment by markosankovic** [comment]
No. This library is only meant to be used in JavaScript projects to parse [ESI](https://www.ethercat.org/en/downloads/downloads_6A46D45EA33C47ECB2BB2686BBA963EC.htm) and manipulate it. We use it for our [OBLAC EtherCAT Design Tool](https://oblac-edt.synapticon.com]) as well as our [source code generator](https://github.com/synapticon/ecatgen). If you have needs for such a library you can read its [generated documentation](https://synapticon.github.io/ecatmod/doc/index.html) or post questions here and I will reply asap.
